<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <link href="/assets/stylesheets/screen.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/assets/stylesheets/global.css" media="screen" rel="stylesheet" type="text/css" >
        <style type="text/css">
            body {
                background: none;
            }
        </style>
    </head>
    <body>
        <div class="container" style="padding: 50px; width: 255px;">
            <?php echo $this->form; ?>
        </div>
    </body>
</html>
