<h2>Верхнее меню</h2>

<?php if (is_null($this->topmenu->getId())) : ?>

    <ul>
        <?php foreach ($this->result as $item): ?>
            <li><a href="/admin/topmenu/edit/?id=<?php echo $item->getId(); ?>"><?php echo $item->getTopMenu(); ?></a></li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>
    <h3><?php echo $this->topmenu->getTopMenu(); ?></h3>
    <?php echo $this->form; ?>
<?php endif; ?>