<div class="filter_left_radius append-bottom">
    <div class="filter_right_radius">
        <div class="filter">
            <a href="/" class="home">&nbsp;</a>
            <a href="#" class="active"><?php echo $this->textpage->getTitle(); ?></a>
        </div>
    </div>
</div>

<div id="content" class="append-bottom">

    <div class="outer">

        <div class="inner">
            <h2><?php echo $this->textpage->getTitle(); ?></h2>
        </div>

    </div>

    <div class="inner">
        <?php echo $this->textpage->getText(); ?>
    </div>                    

</div>

<div class="filter_left_radius append-bottom">
    <div class="filter_right_radius">
        <div class="filter">
            <a href="/" class="home">&nbsp;</a>
            <a href="#" class="active"><?php echo $this->textpage->getTitle(); ?></a>
        </div>
    </div>
</div>